# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"g\n\x19StreamingRecognizeRequest\x12\x15\n\x0b\x61udio_chunk\x18\x01 \x01(\x0cH\x00\x12(\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x16.asr.RecognitionConfigH\x00\x42\t\n\x07request\"6\n\x11RecognitionConfig\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"c\n\x1aStreamingRecognizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x11\n\tminio_key\x18\x04 \x01(\t2e\n\nASRService\x12W\n\x12StreamingRecognize\x12\x1e.asr.StreamingRecognizeRequest\x1a\x1f.asr.StreamingRecognizeResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_start=18
  _globals['_STREAMINGRECOGNIZEREQUEST']._serialized_end=121
  _globals['_RECOGNITIONCONFIG']._serialized_start=123
  _globals['_RECOGNITIONCONFIG']._serialized_end=177
  _globals['_STREAMINGRECOGNIZERESPONSE']._serialized_start=179
  _globals['_STREAMINGRECOGNIZERESPONSE']._serialized_end=278
  _globals['_ASRSERVICE']._serialized_start=280
  _globals['_ASRSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
