# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x03\x61sr\"^\n\x10RecognizeRequest\x12\x15\n\x0b\x61udio_chunk\x18\x01 \x01(\x0cH\x00\x12(\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x16.asr.RecognitionConfigH\x00\x42\t\n\x07request\"6\n\x11RecognitionConfig\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"Z\n\x11RecognizeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x11\n\tminio_key\x18\x04 \x01(\t2J\n\nASRService\x12<\n\tRecognize\x12\x15.asr.RecognizeRequest\x1a\x16.asr.RecognizeResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNIZEREQUEST']._serialized_start=18
  _globals['_RECOGNIZEREQUEST']._serialized_end=112
  _globals['_RECOGNITIONCONFIG']._serialized_start=114
  _globals['_RECOGNITIONCONFIG']._serialized_end=168
  _globals['_RECOGNIZERESPONSE']._serialized_start=170
  _globals['_RECOGNIZERESPONSE']._serialized_end=260
  _globals['_ASRSERVICE']._serialized_start=262
  _globals['_ASRSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
